### ISSUE TITLE
سوال در مورد ساخت بات

### ISSUE THREAD

**Issue by r0zbeh** [Balethon/Balethon#11]
سلام و عرض ادب

میشه در مورد این سناریو که ما بیاییم با پایتون یه کد بنویسیم که از طریق اکانت اصلی مون (نه از طریق بات) به سرور بله وصل بشیم و پیام بفرستیم توضیح بدید که آیا این کار شدنیه و اینکه چطور ممکنه ؟
تااون جایی که من میدونم ما باید ابتدا از طریق get ,post متدها به سرور وصل بشیم و cookie رو دریافت کنیم همچنین یک سری اطلاعات و پارامترهای دیگه هم قابل دریافته بعد از طریق اون با سرور اتصال وب سوکت برقرار کنیم من این مراحل رو انجام دادم اتصال به وب سوکتم هم انجام میشه ولی اطلاعاتی که تو سوکت دریافت میشه ناخواناست و اینکه باچه فرمتی اطلاعات باید ارسال بشه؟

**Comment by MamdMehrabi** [comment]
سلام وقت بخیر
میتونم خروجی ایی که دریافت کردید رو ببینم؟

**Comment by r0zbeh** [comment]
وقتی وب ساکت برقرار میشه ،دیتاها هر چند ثانیه رد بدل میشه هم send هم recive ولی کلا ناخوانا هستن برای مثال این یه نمونه کد دریافتیه 👍 

```
3/

ù«˜œ

```
اینم هگز همونه پیامه 
`0A 33 18 01 12 2F 0A 0A 08 F9 AB 98 9C 07 12 02 10 08 0A 07 08 00 12 03 10 F8 19 0A 09 08 01 12 05 10 FC E2 94 30 0A 0D 08 AA D7 E3 E7 03 12 05 10 89 8E 95`

در کل دیتا ها ناخوانا هستن فک کنم رمز میشن !

**Comment by TheCautious** [comment]
این اطلاعات با فرمت protobuf هستن
برای اینکه بتونید اون ها رو دیسریالایز کنید باید کلاس protobuf مربوط به این درخواست رو داشته باشید
که برای بدست اوردنش باید سر و ته سورس کد اپلیکیشن بله رو دربیارید

**Comment by r0zbeh** [comment]
300000 خط کده :)) اگه وقت شد و تونستید یه سر نخ کلی بدید ممنون میشم! من خیلی وارد نیستم میخوام یه حالت اتوماتیسون بدم برای اکانت اصلی !!
من تابع sendMessage  رو پیدا کردم ولی نمی دونم چطور عمل میکنه !

**Comment by TheCautious** [comment]
پکیج ai.bale.proto توی سورس کد اپلیکیشن بله تمام کلاس های پروتوباف بله داخلش هستن
کد این کلاس ها کامپایل شده ولی میتونید اونا رو بخونید و بر اساس درکتون فایل proto مخصوصشون رو بازنویسی کنید
و درنهایت با استفاده از کامپایلر protoc اون ها رو به کلاس های به راحتی قابل استفاده پایتون تبدیل کنید

**Comment by r0zbeh** [comment]
ممنون چطور میتونم به سورس کد دسترسی داشته باشم؟

**Comment by r0zbeh** [comment]
ممنون میشم راهنمایی کنید !! که سورس رو از کجا گیر بیارم ؟!

**Comment by TheCautious** [comment]
خودم سورس کدش رو با استفاده از ابزار jadx بدست اوردم
